export { default as CopyIcon } from './copy.svg'
export { default as SettingsIcon } from './settings.svg'
export { default as PlusIcon } from './plus.svg'
export { default as ChevronLeftIcon } from './chevron-left.svg'
export { default as ChevronRightIcon } from './chevron-right.svg'
export { default as ExternalIcon } from './external.svg'
export { default as UnknownIcon } from './unknown.svg'